<package format="3">
  <name>ap1_planning</name>
  <version>0.1.0</version>
  <description>Planning node for AP1 project</description>

  <maintainer email="alyashour1@gmail.com">Aly</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>ap1_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
