transitions:
  - from: Driving
    event: ApplicableSignDetected
    to: Stopping
  - from: Stopping 
    event: HasStopped
    to: Stopped 
  - from: Stopped 
    event: StopTimeElapsed
    to: DrivingThrough
  - from: DrivingThrough 
    event: DriveThruDistanceCovered
    to: Driving
# Emergency stop
  - from: Driving 
    event: EmergencyStop
    to: Stopped