name: ROS2 Colcon Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'CMake build type'
        required: false
        default: 'Release'
      run_tests:
        description: 'Run tests after building'
        required: false
        default: 'true'
  push:
    branches: [ "main" ,"colcon_script/logan"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    env:
      BUILD_TYPE: ${{ github.event.inputs.build_type || 'Release' }}
      RUN_TESTS: ${{ github.event.inputs.run_tests || 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Source ROS 2 Jazzy environment
        run: |
          source /opt/ros/jazzy/setup.bash

      - name: Install OS dependencies with rosdep
        run: |
          rosdep update
          rosdep install --from-paths src --ignore-src -iry

      - name: Build workspace with colcon
        run: |
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Source built workspace
        run: |
          source install/setup.bash

      - name: Run tests
        if: ${{ env.RUN_TESTS == 'true' }}
        run: |
          colcon test --packages-select ap1_planning control
          colcon test-result --verbose


