name: ROS2 Colcon Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - colcon_script/logan
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: Release
      RUN_TESTS: 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS 2 Jazzy & Dev Tools
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Initialize and update rosdep
        run: |
          sudo rosdep fix-permissions
          rosdep update
          rosdep install --from-paths src --ignore-src -iry


      - name: Build workspace with colcon
        run: |
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Source built workspace
        run: |
          source install/setup.bash

      - name: Run tests
        if: ${{ env.RUN_TESTS == 'true' }}
        run: |
          colcon test --packages-select ap1_planning control
          colcon test-result --verbose

